### ISSUE TITLE
Project picker says requirements not met even though it's all green

### ISSUE THREAD

**Issue by dividedmind** [applandinc/appmap-intellij-plugin#110]
I tried opening https://github.com/land-of-apps/spring-petclinic — this is the welcome project picker screen:
![intellij-spring-picker](https://user-images.githubusercontent.com/823636/189388640-06fe2dd7-6cbb-44c6-a49f-c6f67a48b280.png)

**Comment by dustinbyrne** [comment]
It does appear to be working as intended with Python
![image](https://user-images.githubusercontent.com/8737782/189396563-a7b53808-506c-4a12-8ac8-ed6c6325d224.png)

**Comment by dividedmind** [comment]
> It does appear to be working as intended with Python

Is it? I think it should say to proceed with caution. Seems like the logic could be inverted here.

**Comment by apotterri** [comment]
It doesn't always work correctly with python, though: 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/4212483/189427516-cf45863d-84a5-47cb-a424-2474c9330213.png">

flaskbb uses pytest as its test runner.

**Comment by jansorg** [comment]
This issue is fixed by https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/e3bc36b17e8265f00ac8a7ab3dd401b59304009d

![image](https://user-images.githubusercontent.com/11473063/189643312-9c931fb3-0015-4222-8224-0ba9a94a4250.png)

![image](https://user-images.githubusercontent.com/11473063/189643230-6a97dd51-5ddf-4017-9c7d-26a0cf3e7190.png)

@apotterri Thanks! That's a new issue, tracking at https://github.com/applandinc/appmap-intellij-plugin/issues/120

**Comment by jansorg** [comment]
Should be fixed with 0.11.0-2, please reopen if it's still a bug on your machine.
https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview
