### ISSUE TITLE
After opening AppMaps from the instructions page, only one AppMap tab is functional

### ISSUE THREAD

**Issue by ahtrotta** [applandinc/appmap-intellij-plugin#91]
To reproduce:

1. Open the `Open AppMaps` instruction page
2. Click on one of the links to an AppMap
3. Then click back to the instruction page
4. Then click back to the AppMap

Now, only one of the tabs will work correctly. The other will be blank.

**Comment by jansorg** [comment]
Thanks! Unfortunately, there's not much we can do about this because the rendering and panel handling is provided by the SDK.
This is hopefully fixed by https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/18c7cbebdde0b4f3c50c01db67bb144448b6d542. I'd be glad if you could test this again with the next update.

**Comment by jansorg** [comment]
Should be fixed, please reopen if this is not working yet for you
