### ISSUE TITLE
Technical Support link to Slack not working in quickstart

### ISSUE THREAD

**Issue by petecheslock** [applandinc/appmap-intellij-plugin#93]
in version `0.8.0-3` - when clicking on the link that says `Stuck? [Technical support available in Slack](https://appmap.io/slack)` clicking the URL opens a blank white page that never loads.

<img width="1503" alt="Screen Shot 2022-08-30 at 3 49 28 PM" src="https://user-images.githubusercontent.com/511733/187529957-5dfdb5cc-68cd-4d90-b523-8935ef583118.png">

**Comment by jansorg** [comment]
Thanks! https://github.com/applandinc/appmap-intellij-plugin/pull/81/commits/20891744ec53117ee82a4c7f396aa8e47cc34825 fixes this problem for the next preview.
Even though external links were supposed to open in the external browser, the JS app's click handler somehow prevented this.

**Comment by petecheslock** [comment]
@jansorg  i grabbed the latest `0.8.0-4 ` to test this PR - oddly it DOES open the link now for slack but it still opens a blank internal browser window - only for slack though not for the docs page.

https://www.loom.com/share/aa2088f2bb524ff58b04e48bb6f7d80d

**Comment by jansorg** [comment]
@petecheslock Thanks!
This is hopefully fixed by 0.8.0-5, now. For unknown reasons the Slack link is not invoking the generic link handler of the web view and the click handler I had was only covering existing links. It's now attached to `document` to inhibit any click action on external links inside the webview.

**Comment by petecheslock** [comment]
Yup - confirmed fixed.
